sample-chat/build.gradle

Please, update stickers library version with several improvements and bugfixes

Update stickers library to 0.2.1

---

sample-chat/src/com/quickblox/sample/chat/ui/activities/ChatActivity.java

We added missed analytics request. Please, update

Added missing analytics request

---

build.gradle
sample-chat/src/main/java/com/quickblox/sample/chat/ui/activity/DialogsActivity.java
sample-chat/src/main/java/com/quickblox/sample/chat/ui/activity/SelectUsersActivity.java

App crashes if the user taps several times 'v' button when he creates a chat

- fixed ANDSAMPLES -130

---

sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/activities/BaseActivity.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/adapters/OpponentsFromCallAdapter.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/fragments/ConversationFragment.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/utils/QBRTCSessionUtils.java
sample-videochat-webrtc/src/main/res/layout/fragment_conversation.xml
sample-videochat-webrtc/src/main/res/values/strings.xml

- updated logic for item onClick for switching between users, setting fullscreen user to preview recycleview and vice versa
- added QBRTCSessionUtils to set status for opponent, etc.

Master.videochat webrtc updated.during call screen updated

---

sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/activities/CallActivity.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/activities/SettingsActivity.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/utils/SeekBarPreference.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/utils/SettingsUtil.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/view/SeekBarPreference.java
sample-videochat-webrtc/src/main/res/layout/seekbar_preference.xml
sample-videochat-webrtc/src/main/res/values/arrays.xml
sample-videochat-webrtc/src/main/res/values/attrs.xml
sample-videochat-webrtc/src/main/res/values/strings.xml
sample-videochat-webrtc/src/main/res/values/styles.xml
sample-videochat-webrtc/src/main/res/xml/preferences.xml

- added new preferences to settings screen;
- created custom view SeekBarPreference for correct displaying new preferences;
- added method for managing new preferences

Master.videochat webrtc updated.new preferences

---

sample-core/src/main/java/com/quickblox/sample/core/utils/SharedPrefsHelper.java
sample-videochat-webrtc/src/main/AndroidManifest.xml
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/activities/BaseActivity.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/activities/CallActivity.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/activities/LoginActivity.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/activities/OpponentsActivity.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/activities/SplashActivity.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/util/QBResRequestExecutor.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/utils/Consts.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/utils/TokenUtils.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/utils/ValidationUtils.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/utils/WebRtcSessionManager.java
sample-videochat-webrtc/src/main/res/values/strings.xml

- перенес старт сервиса на сплешактивити, если есть сохраненный юзер;
- переделал валидацию с посимвольного перебора на regExp;
- поисправлял остальные замечания;

Master.videochat webrtc updated.bug fixing valentyn

---

sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/activities/CallActivity.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/activities/OpponentsActivity.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/db/QbUsersDbManager.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/fragments/BaseConversationFragment.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/fragments/IncomeCallFragment.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/fragments/VideoConversationFragment.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/services/CallService.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/utils/Consts.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/utils/UsersUtils.java
sample-videochat-webrtc/src/main/res/layout/activity_login.xml
sample-videochat-webrtc/src/main/res/values/strings.xml

фикс небольших багов и JIRA
- fixed ANDSAMPLES-191
- fixed ANDSAMPLES-203	
- fixed ANDSAMPLES-186	
- fixed ANDSAMPLES-215

Master.videochat webrtc updated.fixing bugs from jira

---

sample-videochat-webrtc/build.gradle
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/activities/CallActivity.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/activities/OpponentsActivity.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/fragments/AudioConversationFragment.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/fragments/BaseConversationFragment.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/fragments/ConversationFragmentCallbackListener.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/fragments/VideoConversationFragment.java
sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/utils/SettingsUtil.java
sample-videochat-webrtc/src/main/res/drawable/selector_toggle_speaker.xml
sample-videochat-webrtc/src/main/res/menu/conversation_fragment.xml

- made speaker default in Video and receiver in Audio call
- fixed case when opponent list is not actual
- fixed crash if  opponent == null in CallActivity
- fixed problem with headset in both fragments (plugged or unplugged state with icons)
- fixed size of local preview screen in multi call case
- fixed set default video format after changing to custom value
- added method sendHeadsetState() CallActivity if incoming call, for actual state of the headset

Master.videochat webrtc updated bug fixing roman

---

sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/fragments/VideoConversationFragment.java
sample-videochat-webrtc/src/main/res/menu/conversation_fragment.xml

delete audioswitch button in VideoConversationFragment

---

README.md

- updated tutorial with import SDK library from local repo
- 

update tutorial with local repo

---

README.md

add as example sample chat to proguard

---

sample-custom-objects/src/main/java/com/quickblox/sample/customobjects/activities/AddNewMovieActivity.java
sample-custom-objects/src/main/java/com/quickblox/sample/customobjects/activities/MovieListActivity.java
sample-custom-objects/src/main/java/com/quickblox/sample/customobjects/activities/SplashActivity.java
sample-custom-objects/src/main/java/com/quickblox/sample/customobjects/utils/QBCustomObjectsUtils.java

add checkQBException

---

snippets/src/main/java/com/sdk/snippets/modules/SnippetsAuth.java
snippets/src/main/java/com/sdk/snippets/modules/SnippetsChat.java
snippets/src/main/java/com/sdk/snippets/modules/SnippetsContent.java
snippets/src/main/java/com/sdk/snippets/modules/SnippetsCustomObjects.java
snippets/src/main/java/com/sdk/snippets/modules/SnippetsLocation.java
snippets/src/main/java/com/sdk/snippets/modules/SnippetsPushNotifications.java
snippets/src/main/java/com/sdk/snippets/modules/SnippetsUsers.java

- rewrote all REST requests for new API;
- rewrote chat logic for new chat API;

- adapted code for working with new SDK API v.3.0

---

snippets/src/main/java/com/sdk/snippets/modules/SnippetsChat.java
snippets/src/main/res/raw/servers.json

- adapted snippets to new API (v.3.0)

Feature/adapt snipets to 3.0

---

build.gradle
sample-chat/src/main/java/com/quickblox/sample/chat/managers/DialogsManager.java
sample-chat/src/main/java/com/quickblox/sample/chat/ui/adapter/DialogsAdapter.java
sample-chat/src/main/java/com/quickblox/sample/chat/utils/chat/ChatHelper.java

- remove moving some some callbacks to UI;
- prepare for release;

- prepare for release;

---

sample-custom-objects/build.gradle

add dependency rxandroid version 1.2.1

---

snippets/src/main/java/com/sdk/snippets/Application.java
snippets/src/main/java/com/sdk/snippets/modules/SnippetsAuth.java
snippets/src/main/java/com/sdk/snippets/modules/SnippetsChat.java
snippets/src/main/java/com/sdk/snippets/modules/SnippetsContent.java

- some fixes after updating SDK to 3.3.0
- tested manually: create session (with/without user), login to chat, create dialogs...

Fix compiling errors in 'snippets' project

---

sample-videochat-conference/build.gradle
sample-videochat-conference/src/main/java/com/quickblox/sample/conference/activities/CallActivity.java
sample-videochat-conference/src/main/java/com/quickblox/sample/conference/fragments/AudioConversationFragment.java

add audioSwitchToggleButton to AudioConversationFragment

---

build.gradle
sample-chat/src/main/res/layout/activity_dialogs.xml
sample-chat/src/main/res/values/styles_widgets.xml
sample-core/src/main/res/values/styles_widgets.xml
sample-custom-objects/src/main/res/layout/activity_add_movie.xml
sample-custom-objects/src/main/res/layout/activity_movie.xml
sample-pushnotifications/src/main/res/values/styles_widgets.xml
sample-users/src/main/res/layout/activity_sign_in.xml
sample-users/src/main/res/layout/activity_sign_up.xml
sample-users/src/main/res/layout/list_item_user.xml
sample-users/src/main/res/values/styles.xml

update version to 3.4.1

---

artifacts.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties
sample-chat/build.gradle
sample-content/build.gradle
sample-core/build.gradle
sample-custom-objects/build.gradle
sample-pushnotifications/build.gradle
sample-users/build.gradle
sample-videochat-webrtc/build.gradle
snippets/build.gradle

update gradle to latest version (3.0.1) (QBANDRSDK-666)

---

sample-chat/src/main/java/com/quickblox/sample/chat/utils/chat/ChatHelper.java

- Removed iterator, which cuts off all public dialogs.
1. Log in as any user -> Chats screen appears
2. Verify Public chats
Any updates needed

removed iterator, which cuts all public dialogs

---

sample-chat/src/main/java/com/quickblox/sample/chat/ui/activity/ChatActivity.java
sample-chat/src/main/java/com/quickblox/sample/chat/ui/adapter/ChatAdapter.java
sample-chat/src/main/java/com/quickblox/sample/chat/utils/chat/ChatHelper.java

- fixed attachment properties to use the same behavior like in iOS samples 
- fixed displaying phtos from iOS devices
- Open any chat who has received photos
- Open any photo fro iOS or Android device
All received photos should be opened
In documentation should be described the approach to sending and receiving attachments.

ANDSAMPLES-503

---

sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/utils/chat/ChatHelper.java
sample-chat-kotlin/app/src/main/java/com/quickblox/sample/chat/kotlin/utils/chat/ChatHelper.kt

- removed public URLs from attachments in Java and Kotlin samples

Removed public URLs from attachments

---

sample-videochat-kotlin/app/build.gradle
sample-videochat-kotlin/app/src/main/java/com/quickblox/sample/videochat/kotlin/activities/CallActivity.kt
sample-videochat-kotlin/app/src/main/java/com/quickblox/sample/videochat/kotlin/activities/LoginActivity.kt
sample-videochat-kotlin/app/src/main/java/com/quickblox/sample/videochat/kotlin/activities/OpponentsActivity.kt
sample-videochat-kotlin/app/src/main/java/com/quickblox/sample/videochat/kotlin/fragments/BaseConversationFragment.kt
sample-videochat-kotlin/app/src/main/java/com/quickblox/sample/videochat/kotlin/fragments/VideoConversationFragment.kt
sample-videochat-kotlin/app/src/main/java/com/quickblox/sample/videochat/kotlin/services/CallService.kt
sample-videochat-kotlin/app/src/main/java/com/quickblox/sample/videochat/kotlin/utils/Consts.kt
sample-videochat-kotlin/app/src/main/java/com/quickblox/sample/videochat/kotlin/utils/PushNotificationSender.kt
sample-videochat-kotlin/app/src/main/java/com/quickblox/sample/videochat/kotlin/utils/ValidationUtils.kt
sample-videochat-kotlin/app/src/main/res/values/strings.xml

- fixed Pushes to iOS and login and fullname requirements

[VideoChat][Kotlin] Voip Pushes to iOS and login and fullname requirements

---

sample-chat-java/app/build.gradle
sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/App.java
sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/managers/BackgroundListener.java
sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/ui/activity/BaseActivity.java
sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/ui/activity/ChatActivity.java
sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/ui/activity/DialogsActivity.java
sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/ui/activity/LoginActivity.java
sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/ui/activity/SplashActivity.java
sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/ui/adapter/ChatAdapter.java
sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/utils/ValidationUtils.java
sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/utils/chat/ChatHelper.java
sample-chat-java/app/src/main/res/values/strings.xml
sample-chat-kotlin/app/build.gradle
sample-chat-kotlin/app/src/main/java/com/quickblox/sample/chat/kotlin/App.kt
sample-chat-kotlin/app/src/main/java/com/quickblox/sample/chat/kotlin/managers/BackgroundListener.kt
sample-chat-kotlin/app/src/main/java/com/quickblox/sample/chat/kotlin/ui/activity/BaseActivity.kt
sample-chat-kotlin/app/src/main/java/com/quickblox/sample/chat/kotlin/ui/activity/ChatActivity.kt
sample-chat-kotlin/app/src/main/java/com/quickblox/sample/chat/kotlin/ui/activity/DialogsActivity.kt
sample-chat-kotlin/app/src/main/java/com/quickblox/sample/chat/kotlin/ui/activity/LoginActivity.kt
sample-chat-kotlin/app/src/main/java/com/quickblox/sample/chat/kotlin/ui/activity/SelectUsersActivity.kt
sample-chat-kotlin/app/src/main/java/com/quickblox/sample/chat/kotlin/ui/activity/SplashActivity.kt
sample-chat-kotlin/app/src/main/java/com/quickblox/sample/chat/kotlin/ui/adapter/ChatAdapter.kt
sample-chat-kotlin/app/src/main/java/com/quickblox/sample/chat/kotlin/utils/SharedPrefsHelper.kt
sample-chat-kotlin/app/src/main/java/com/quickblox/sample/chat/kotlin/utils/ValidationUtils.kt
sample-chat-kotlin/app/src/main/java/com/quickblox/sample/chat/kotlin/utils/chat/ChatHelper.kt
sample-chat-kotlin/app/src/main/res/values/strings.xml

- changed requirements of fields on Login Screen (login and username)
- added background mode feature. Now samples are offline in the background and reconnect and become online when the user returns to the sample application.
- pushnotifications are available only in the background. 
- minor bug fixes 
The samples should be completely retested
Any documentation updates aren't needed

Uploaded new version of chat samples

---

sample-videochat-java/app/build.gradle
sample-videochat-java/app/src/main/java/com/quickblox/sample/videochat/java/activities/CallActivity.java
sample-videochat-java/app/src/main/java/com/quickblox/sample/videochat/java/services/CallService.java
sample-videochat-java/build.gradle
sample-videochat-kotlin/.gitignore
sample-videochat-kotlin/app/build.gradle
sample-videochat-kotlin/app/src/main/java/com/quickblox/sample/videochat/kotlin/activities/CallActivity.kt
sample-videochat-kotlin/app/src/main/java/com/quickblox/sample/videochat/kotlin/services/CallService.kt
sample-videochat-kotlin/build.gradle

2. made changes to handle QB-SDK changes related to multi-user calling
- updated QB-SDK version to 3.9.2
- made changes to handle QB-SDK changes related to multi-user calling
x
x

Update QB-SDK version to 3.9.2 and changes related to multi-user calling

---

sample-videochat-java/app/build.gradle
sample-videochat-java/app/src/main/java/com/quickblox/sample/videochat/java/activities/OpponentsActivity.java
sample-videochat-java/app/src/main/java/com/quickblox/sample/videochat/java/util/QBResRequestExecutor.java
sample-videochat-kotlin/app/build.gradle
sample-videochat-kotlin/app/src/main/java/com/quickblox/sample/videochat/kotlin/activities/OpponentsActivity.kt

- fixed logout logic without firebase 
- fixed crash in public chats
- update QB SDK
sample was tested
documentation updates are available

[VideoChat][Java][Kotlin] Fixed logout logic without firebase, crash in public chats

---

sample-conference-kotlin/app/build.gradle
sample-conference-kotlin/app/src/main/AndroidManifest.xml
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/App.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/data/call/CallRepositoryImpl.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/domain/call/CallListener.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/domain/call/CallManager.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/domain/call/CallManagerImpl.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/domain/call/ReconnectionListener.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/domain/call/entities/CallEntity.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/domain/call/entities/CallEntityImpl.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/domain/call/entities/SessionState.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/domain/call/entities/SessionStateImpl.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/presentation/screens/call/CallActivity.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/presentation/screens/call/CallViewModel.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/presentation/screens/call/CustomLinearLayout.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/presentation/screens/call/ViewState.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/presentation/screens/chat/ChatViewModel.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/presentation/screens/chat/adapters/message/ChatAdapter.kt
sample-conference-kotlin/app/src/main/java/com/quickblox/sample/conference/kotlin/presentation/screens/muteparticipants/MuteParticipantsViewModel.kt
sample-conference-kotlin/app/src/main/res/layout/activity_call.xml
sample-conference-kotlin/app/src/main/res/values/strings.xml
sample-conference-kotlin/build.gradle

1.1.0-conference-kotlin

---

sample-conference-java/app/build.gradle
sample-conference-java/app/google-services.json
sample-conference-java/app/proguard-rules.pro
sample-conference-java/app/src/main/AndroidManifest.xml
sample-conference-java/app/src/main/java/com/quickblox/sample/videochat/conference/java/App.java
sample-conference-java/app/src/main/java/com/quickblox/sample/videochat/conference/java/activities/AppInfoActivity.java
sample-conference-java/app/src/main/java/com/quickblox/sample/videochat/conference/java/activities/AttachmentImageActivity.java
sample-conference-java/app/src/main/java/com/quickblox/sample/videochat/conference/java/adapters/ChatAdapter.java
sample-conference-java/app/src/main/java/com/quickblox/sample/videochat/conference/java/fcm/NotificationUtils.java
sample-conference-java/app/src/main/java/com/quickblox/sample/videochat/conference/java/services/CallService.java
sample-conference-java/build.gradle
sample-conference-java/gradle/wrapper/gradle-wrapper.properties

4.4.1-conference-java

---

sample-chat-java/app/build.gradle
sample-chat-java/app/google-services.json
sample-chat-java/app/proguard-rules.pro
sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/App.java
sample-chat-java/app/src/main/java/com/quickblox/sample/chat/java/utils/NotificationUtils.java
sample-chat-java/build.gradle

4.2.9-chat-java

---

sample-pushnotifications-java/app/build.gradle
sample-pushnotifications-java/app/proguard-rules.pro
sample-pushnotifications-java/build.gradle

4.0.3-push-java

---

sample-pushnotifications-kotlin/app/build.gradle
sample-pushnotifications-kotlin/app/proguard-rules.pro
sample-pushnotifications-kotlin/build.gradle

4.0.3-push-kotlin

---

android-ui-kit-sample/app/build.gradle

1.0.1-ui-kit

---

android-ui-kit-sample/app/build.gradle

1.0.2-ui-kit

---

android-ui-kit-sample/README.md
android-ui-kit-sample/app/build.gradle
android-ui-kit-sample/settings.gradle

Rc 1.1.0 UI kit

---

android-ui-kit-sample/README.md
android-ui-kit-sample/app/build.gradle
android-ui-kit-sample/app/src/main/AndroidManifest.xml
android-ui-kit-sample/app/src/main/java/com/example/android_ui_kit_sample/LoginActivity.kt
android-ui-kit-sample/app/src/main/java/com/example/android_ui_kit_sample/SignUpActivity.kt
android-ui-kit-sample/app/src/main/res/layout/activity_login.xml
android-ui-kit-sample/app/src/main/res/layout/activity_signup.xml
android-ui-kit-sample/app/src/main/res/values-night/themes.xml
android-ui-kit-sample/app/src/main/res/values/strings.xml
android-ui-kit-sample/app/src/main/res/values/themes.xml
android-ui-kit-sample/settings.gradle

1.3.0-ui-kit
